version: "3.8"

services:
  career-roadmap:
    container_name: cra
    build:
      context: .

    # image: noelav07/career_roadmap_assistance:3.0
    restart: always
    ports:
      - "8501:8501"
      - "8502:8502"
      - "8503:8503"
    env_file:
      - .env